Feature/7
Yuma-Tsukakoshi/tech-app pull request #26
Opened 2023-03-16 23:09 UTC by Yuma-Tsukakoshi

2023-03-16 23:11 UTC, Yuma-Tsukakoshi commented
### TODO
非同期通信でデータ取得　ー＞　自動更新

＜メモ＞
まだマージしないでください

2023-03-19 07:36 UTC, kazuki1023 requested changes
肝心のph1の詳細ページが見れない
あと、質問ページのレスポンシブほしいです

2023-03-19 07:36 UTC, kazuki1023 commented on src/routes/web.php
<img width="1440" alt="Screen Shot 2023-03-19 at 7 32 44" src="https://user-images.githubusercontent.com/107235222/226160617-b48c9d54-b407-4053-b920-5bf71e4370e2.png">


ルーティングあってる？？？

2023-03-19 07:36 UTC, kazuki1023 commented on src/resources/views/layouts/each_ph_answer.blade.php
latoutで枠作って、そこにはめ込むのすごくいいと思う！！！

2023-03-19 07:52 UTC, Yuma-Tsukakoshi commented on src/resources/views/layouts/each_ph_answer.blade.php
ありがとう！

2023-03-19 08:30 UTC, Yuma-Tsukakoshi commented on src/routes/web.php
カズとdiscordで解決済み

2023-03-19 08:30 UTC, merged